In [2]:
print("hello")

hello


In [7]:
from typing import no_type_check
import numpy as np

list=[34,456,454,67,7]
np_array=np.array([1,2,3,4,5,7])
print(np_array)

[1 2 3 4 5 7]


In [14]:
np_array1=np.array([[23,435,56,67],[34,45]])
print(np_array1)

[list([23, 435, 56, 67]) list([34, 45])]


<ipython-input-14-be5b05a28026>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np_array1=np.array([[23,435,56,67],[34,45]])


In [9]:
np.linspace(-10, 10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
a=np.arange(12,24).reshape(3,4)
print(a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [17]:
#np.sqrt(15)
np.sqrt(455)

21.330729007701542